feign:
  client:
    config:
      ## feign name
      invokerFeignName:
        connectTimeout: 50000

spring:
  application:
  jackson:
    default-property-inclusion: non_null
    name: feign-consumer