feign:
  client:
    config:
      ## feign name
      invokerFeignName:
        connectTimeout: 50000
logging:
  level:
    root: DEBUG
spring:

  output:
    ansi:
      enabled: ALWAYS
  application:
  jackson:
    default-property-inclusion: non_null
    name: feign-consumer